Limit torch version in setup.py and requirements.txt
Using 1.6.0 with stanza 1.0.1 leads to:
RuntimeError: Integer division of tensors using div or / is no longer
supported, and in a future release div will perform true division as in
Python 3. Use true_divide or floor_divide (// in Python) instead.